CFLAGS=-Wall -g -std=c99

all: ex1 ex3

clean:
	rm -f ex[:digit:]+

#EX2 Extra Credit
# 1.Create an all: ex1 target that will build ex1 with just the command make.
# 2.Read man make to find out more information on how to run it.
# 3.Read man cc to find out more information on what the flags -Wall and -g do.
# A: -g    adds debugging information to the executable file
#    -Wall turns on most, but not all, compiler warnings
# 4.Research Makefiles online and see if you can improve this one even more.
# 5.Find a Makefile in another C project and try to understand what it's doing.
